server:
  port: 8888

spring:
  profiles:
    active: native, git, vault
  application:
    name: configserver
  cloud:
    config:
      server:
        native:
          searchLocations: file:///home/isvar/Documents/sensibleEjemplo/spring-cloud-configserver-vault-master/config-repo
        git:
          uri: https://github.com/Isabraxas/cygnus-config
        vault:
          port: 8200
          host: 127.0.01
          default-key: ${other.default.key:application}

password: provicional